Repository etclabscore/jade-website, pull requests merged in 2019-07, with the labels that each got.

#1 fix(circleci): add cloudfront invalidation
  .circleci/config.yml
Labels: bug

#2 fix: cloudfront id
  .circleci/config.yml
Labels: bug

#6 fix(learn): add Lets Talk ETC episode with zane
  docs/learn/index.md
Labels: enhancement

#7 fix(learn): extra asterisk
  docs/learn/index.md
Labels: bug, documentation
